apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      task: monitoring
      k8s-app: influxdb
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.1.0
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-storage
      volumes:
        - name: influxdb-storage
          nfs:
            server: 192.168.31.132
            path: /influxdb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-system
spec:
   type: NodePort
   selector:
      k8s-app: influxdb
   ports:
    - name: api
      protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 30109
    - name: gui
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30119
